apiVersion: apps/v1
kind: Deployment
metadata:
  name: buscador-ifindit-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buscador-ifindit-react
  template:
    metadata:
      labels:
        app: buscador-ifindit-react
    spec:
      containers:
        - name: buscador-ifindit-react-container
          image: localhost:5000/buscador-ifindit-react:1.0
          resources: {}    
          securityContext:
            runAsUser: 0
          volumeMounts:
          - mountPath: /opt/react-frontend-custom-enviroment/.env
            name: react-frontend-custom-enviroment
            subPath: .env
      volumes:
        - name: react-frontend-custom-enviroment
          configMap:
            name: buscador-ifindit-react-config
